# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d1a10e67b86ed05d5de91309c3a1b9a4956f611ed4c8cbf04a002c7d8b42fc6e800aef0fcf33dfd4d5197d89cb5dc5c354145f8a755b27ae078575cbee88c4d

test:
  secret_key_base: 995decb7406e9ea255ef1c3d7eecabdf488807df33f44b0d22a1323de445e8ddc7dee69fc4f0b5f3aa7846de9a28e9ab32532df7797eea3d77a53d58ade4f0aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
